name: Fischbestand
options:
  bundleIdPrefix: com.simonmaiwald
  deploymentTarget:
    iOS: "16.0"

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    branch: main
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation
    from: "0.9.0"

targets:
  Fischbestand:
    type: application
    platform: iOS
    sources:
      - path: Fischbestand
        excludes:
          - FischbestandTests/**
          - FischbestandUITests/**
    resources:
      - path: Fischbestand/Resources
    info:
      path: Fischbestand/Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.simonmaiwald.fischbestand
        DEVELOPMENT_TEAM: XDLCKT3P87
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: WhisperKit
      - package: ZIPFoundation
  FischbestandTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Fischbestand/FischbestandTests
    dependencies:
      - target: Fischbestand
